name: agrimarket

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: agrimarket
    command: start:prod
    ports:
      - 3030:3000
    networks:
      - agrimarket
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16.6-alpine
    container_name: agrimarket-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - agrimarket
    restart: always

volumes:
  pg_data:

networks:
  agrimarket:
    driver: bridge
